# Generated by Django 5.1.5 on 2025-01-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_app_created_by_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
