# Generated by Django 5.1.5 on 2025-01-20 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_populate_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='slug',
        ),
    ]
