# Generated by Django 5.1.5 on 2025-01-20 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customuser_points_earner_customuser_screenshot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='points_earner',
            new_name='points_earned',
        ),
    ]
